### PR TITLE
chore: new logo

### PR DESCRIPTION
**Pull request by azhsetiawan**
Hi,
Here is a new **anoman** logo, `svg` and `png` inside assets folder.
Hope you like it.

### CODE REVIEW

**Review by bxcodec — APPROVED** [review]
LGTM

**Comment by bxcodec** [comment]
Jempol 👍

**Comment by wuriyanto48** [comment]
@bxcodec , kenalin nih @azhsetiawan , di desainer, :D,
kalo butuh logo buat project di golangid, bisa request hehe

**Comment by bxcodec** [comment]
Siaappppppp mas @wuriyanto48 
Salam kenal @azhsetiawan

**Comment by azhsetiawan** [comment]
salam kenal mas @bxcodec 
nanti saya ikutan berkontribusi di bagian design dulu ya

**Pull request merged**
